spring.application.name=RoleBasedAccess

spring.datasource.url=jdbc:mysql://localhost:3306/manojdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql123


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


jwt.secret=36Va+8E33kGC3TPV3MX2GJffcjKWgW5OksI9qdNUwrg=